using Microsoft.EntityFrameworkCore;
using SolarShield.Core.DTOs;
using SolarShield.Core.Entities;
using SolarShield.Core.Enums;
using SolarShield.Infrastructure.Data;

namespace SolarShield.API.Services;

public class TaskService
{
    private readonly ApplicationDbContext _db;
    private readonly AccessControlService _access;

    public TaskService(ApplicationDbContext db, AccessControlService access)
    {
        _db = db;
        _access = access;
    }

    public async Task<List<TaskDto>> GetTasksAsync(int? siteId, int? assigneeId, string? status, int userId, UserRole role, int? organizationId)
    {
        var accessibleIds = await _access.GetAccessibleSiteIdsAsync(userId, role, organizationId);
        if (accessibleIds.Count == 0) return [];

        var query = _db.WorkTasks.AsNoTracking().AsQueryable();

        if (siteId.HasValue)
        {
            if (!accessibleIds.Contains(siteId.Value)) return [];
            query = query.Where(t => t.SiteId == siteId.Value);
        }
        else
        {
            query = query.Where(t => accessibleIds.Contains(t.SiteId));
        }

        if (assigneeId.HasValue) query = query.Where(t => t.AssignedToUserId == assigneeId);
        if (!string.IsNullOrEmpty(status) && Enum.TryParse<WorkTaskStatus>(status, true, out var st))
            query = query.Where(t => t.Status == st);

        return await query
            .OrderByDescending(t => t.ScheduledAt)
            .Select(t => new TaskDto(
                t.Id, t.SiteId, t.Site.Name, t.ZoneId, t.Zone != null ? t.Zone.Name : null,
                t.Title, t.Description, t.Status.ToString(),
                t.AssignedTo != null ? t.AssignedTo.FullName : null, t.AssignedToUserId, t.IsAutoGenerated,
                t.ScheduledAt, t.StartedAt, t.CompletedAt, t.PhotoUrl, t.LocationLabel))
            .ToListAsync();
    }

    public async Task<TaskDto?> GetTaskByIdAsync(int id, int userId, UserRole role, int? organizationId)
    {
        var task = await _db.WorkTasks
            .Include(t => t.Site).Include(t => t.Zone).Include(t => t.AssignedTo)
            .FirstOrDefaultAsync(t => t.Id == id);
        if (task == null) return null;
        if (!await _access.CanAccessSiteAsync(userId, role, organizationId, task.SiteId))
            return null;
        return MapTask(task);
    }

    public async Task<TaskDto> CreateTaskAsync(CreateTaskRequest request, int createdByUserId)
    {
        var task = new WorkTask
        {
            SiteId = request.SiteId,
            ZoneId = request.ZoneId,
            Title = request.Title,
            Description = request.Description,
            AssignedToUserId = request.AssignedToUserId,
            ScheduledAt = request.ScheduledAt,
            LocationLabel = request.LocationLabel,
            CreatedByUserId = createdByUserId
        };
        _db.WorkTasks.Add(task);
        await _db.SaveChangesAsync();
        return MapTask(await _db.WorkTasks.Include(t => t.Site).Include(t => t.Zone).Include(t => t.AssignedTo).FirstAsync(t => t.Id == task.Id));
    }

    public async Task<TaskDto?> UpdateTaskAsync(int id, UpdateTaskRequest request)
    {
        var task = await _db.WorkTasks.FindAsync(id);
        if (task == null) return null;

        if (!string.IsNullOrEmpty(request.Status))
        {
            var newStatus = Enum.Parse<WorkTaskStatus>(request.Status, true);
            task.Status = newStatus;
            if (newStatus == WorkTaskStatus.InProgress && !task.StartedAt.HasValue)
                task.StartedAt = DateTime.UtcNow;
            if (newStatus == WorkTaskStatus.Done)
                task.CompletedAt = DateTime.UtcNow;
        }
        if (request.PhotoUrl != null) task.PhotoUrl = request.PhotoUrl;
        if (request.Description != null) task.Description = request.Description;

        await _db.SaveChangesAsync();
        return MapTask(await _db.WorkTasks.Include(t => t.Site).Include(t => t.Zone).Include(t => t.AssignedTo).FirstAsync(t => t.Id == id));
    }

    public async Task<TaskDto?> CreateFromFaultAsync(int faultId, int? assignedToUserId, int createdByUserId)
    {
        var fault = await _db.Faults.Include(f => f.Zone).FirstOrDefaultAsync(f => f.Id == faultId);
        if (fault == null) return null;

        var task = new WorkTask
        {
            SiteId = fault.SiteId,
            ZoneId = fault.ZoneId,
            Title = $"WO: {fault.Title}",
            Description = $"Maintenance work order from alert #{fault.Id}. {fault.Description}",
            AssignedToUserId = assignedToUserId ?? fault.AssignedToUserId,
            CreatedByUserId = createdByUserId,
            IsAutoGenerated = true,
            ScheduledAt = DateTime.UtcNow.AddHours(4),
            LocationLabel = fault.Zone?.Name ?? "Site-wide"
        };
        _db.WorkTasks.Add(task);
        fault.Status = FaultStatus.Assigned;
        await _db.SaveChangesAsync();
        return MapTask(await _db.WorkTasks.Include(t => t.Site).Include(t => t.Zone).Include(t => t.AssignedTo).FirstAsync(t => t.Id == task.Id));
    }

    private static TaskDto MapTask(WorkTask t) => new(
        t.Id, t.SiteId, t.Site?.Name ?? "", t.ZoneId, t.Zone?.Name,
        t.Title, t.Description, t.Status.ToString(),
        t.AssignedTo?.FullName, t.AssignedToUserId, t.IsAutoGenerated,
        t.ScheduledAt, t.StartedAt, t.CompletedAt, t.PhotoUrl, t.LocationLabel
    );
}
