using SolarShield.Core.Enums;

namespace SolarShield.Core.Entities;

public class WorkTask
{
    public int Id { get; set; }
    public int SiteId { get; set; }
    public int? ZoneId { get; set; }
    public string Title { get; set; } = string.Empty;
    public string Description { get; set; } = string.Empty;
    public WorkTaskStatus Status { get; set; } = WorkTaskStatus.Open;
    public int? AssignedToUserId { get; set; }
    public int? CreatedByUserId { get; set; }
    public bool IsAutoGenerated { get; set; }
    public DateTime? ScheduledAt { get; set; }
    public DateTime? StartedAt { get; set; }
    public DateTime? CompletedAt { get; set; }
    public string? PhotoUrl { get; set; }
    public string? LocationLabel { get; set; }
    public double? Latitude { get; set; }
    public double? Longitude { get; set; }

    public SolarSite Site { get; set; } = null!;
    public Zone? Zone { get; set; }
    public User? AssignedTo { get; set; }
    public User? CreatedBy { get; set; }
}
