export interface SiteSummary {
  id: number;
  name: string;
  location: string;
  capacityMw: number;
  latitude: number;
  longitude: number;
  targetPr: number;
  organizationId?: number;
  plantCode?: string;
  organizationName?: string;
}

export interface LoginResponse {
  token: string;
  userId: number;
  fullName: string;
  email: string;
  role: string;
  preferredLanguage: string;
  organizationId?: number;
  organizationName?: string;
  accessibleSites: SiteSummary[];
}

export interface Organization {
  id: number;
  name: string;
  code: string;
  contactEmail?: string;
  subscriptionPlan: string;
  maxPlants: number;
  plantCount: number;
  userCount: number;
  totalCapacityMw: number;
  isActive: boolean;
  createdAt: string;
}

export interface PlatformStats {
  totalOrganizations: number;
  activeOrganizations: number;
  totalPlants: number;
  totalCapacityMw: number;
  totalUsers: number;
  openFaults: number;
  pendingTasks: number;
  criticalAlerts?: number;
  activeSubscriptions?: number;
  expiringSoon?: number;
  monthlyRevenue?: number;
}

export interface AdminUser {
  id: number;
  fullName: string;
  email: string;
  phone: string;
  role: string;
  organizationId?: number;
  organizationName?: string;
  isActive: boolean;
  assignedSites: SiteSummary[];
  createdAt: string;
}

export interface DashboardSummary {
  faultsToday: number;
  criticalFaults: number;
  pendingTasks: number;
  currentPr: number;
  soilingIndex: number;
  todayGenerationKwh: number;
  targetGenerationKwh: number;
  siteName: string;
  siteId: number;
  energyLossKwh?: number;
  energyLossPercent?: number;
  onlineAssets?: number;
  totalAssets?: number;
  equipmentHealthAvg?: number;
}

export interface Fault {
  id: number;
  siteId: number;
  siteName: string;
  zoneId?: number;
  zoneName?: string;
  type: string;
  severity: string;
  status: string;
  title: string;
  description: string;
  isPredicted: boolean;
  confidenceScore?: number;
  assignedToName?: string;
  assignedToUserId?: number;
  fixNotes?: string;
  photoUrl?: string;
  detectedAt: string;
  resolvedAt?: string;
}

export interface WorkTask {
  id: number;
  siteId: number;
  siteName: string;
  zoneId?: number;
  zoneName?: string;
  title: string;
  description: string;
  status: string;
  assignedToName?: string;
  assignedToUserId?: number;
  isAutoGenerated: boolean;
  scheduledAt?: string;
  startedAt?: string;
  completedAt?: string;
  photoUrl?: string;
  locationLabel?: string;
}

export interface CleaningSchedule {
  id: number;
  siteId: number;
  zoneId: number;
  zoneName: string;
  scheduledDate: string;
  completedDate?: string;
  soilingIndexAtSchedule: number;
  priority: number;
  isCompleted: boolean;
  photoProofUrl?: string;
}

export interface ZoneSoiling {
  zoneId: number;
  zoneName: string;
  stringId: string;
  soilingIndex: number;
  estimatedLossPercent: number;
  lastUpdated: string;
  priorityLevel: string;
}

export interface GenerationAnalytics {
  date: string;
  actualKwh: number;
  theoreticalKwh: number;
  performanceRatio: number;
  irradiance: number;
  temperature: number;
}

export interface FaultSummary {
  id: number;
  title: string;
  severity: string;
  status: string;
  zoneName?: string;
  detectedAt: string;
}

export interface AnalyticsSummary {
  dailyGeneration: GenerationAnalytics[];
  zoneSoiling: ZoneSoiling[];
  totalFaultsOpen: number;
  tasksCompletedThisWeek: number;
  tasksPending: number;
  avgPr7Days: number;
  totalActualKwh: number;
  totalTheoreticalKwh: number;
  avgSoilingIndex: number;
  openFaults: FaultSummary[];
}

export interface Notification {
  id: number;
  title: string;
  message: string;
  isRead: boolean;
  createdAt: string;
  linkType?: string;
  linkId?: number;
}

export interface UserProfile {
  id: number;
  fullName: string;
  email: string;
  phone: string;
  role: string;
  preferredLanguage: string;
  organizationId?: number;
  organizationName?: string;
  assignedSites: SiteSummary[];
  permissions: string[];
}

export const SUPER_ADMIN_ROLES = ['SuperAdmin'];
export const COMPANY_ADMIN_ROLES = ['SuperAdmin', 'CompanyAdmin', 'CompanyTechnicalAdmin', 'Admin'];
export const PLANT_ADMIN_ROLES = ['SuperAdmin', 'CompanyAdmin', 'CompanyTechnicalAdmin', 'PlantAdmin', 'Admin'];
export const ANALYTICS_ROLES = ['SuperAdmin', 'CompanyAdmin', 'CompanyTechnicalAdmin', 'PlantAdmin', 'Supervisor', 'Admin'];
export const BILLING_ROLES = ['SuperAdmin', 'CompanyAdmin', 'Admin'];

export interface Asset {
  id: number;
  siteId: number;
  siteName: string;
  zoneId?: number;
  zoneName?: string;
  assetCode: string;
  type: string;
  serialNumber: string;
  manufacturer: string;
  model: string;
  installationDate?: string;
  capacityKw: number;
  location: string;
  status: string;
  healthScore: number;
  lastMaintenanceAt?: string;
}

export interface ScadaSnapshot {
  siteId: number;
  siteName: string;
  voltage: number;
  current: number;
  powerKw: number;
  temperature: number;
  frequency: number;
  inverterStatus: string;
  communicationStatus: string;
  energyGenerationKwh: number;
  recordedAt: string;
  assets: AssetScada[];
}

export interface AssetScada {
  assetId: number;
  assetCode: string;
  type: string;
  powerKw: number;
  temperature: number;
  status: string;
  healthScore: number;
}

export interface CompanyDashboard {
  totalPlants: number;
  totalCapacityMw: number;
  onlineAssets: number;
  totalAssets: number;
  criticalAlerts: number;
  openMaintenance: number;
  todayGenerationKwh: number;
  targetGenerationKwh: number;
  energyLossKwh: number;
  plantEfficiency: number;
  equipmentHealth: number;
  aiDetectedIssues: number;
  activeIssues: number;
}

export interface OperationsEfficiency {
  plants: number;
  mwMonitored: number;
  assets: number;
  activeIssues: number;
  aiDetectedIssues: number;
  maintenanceTasks: number;
  criticalTasks: number;
  normalTasks: number;
  remoteMonitoringCoverage: number;
}

export interface EnergyLoss {
  expectedGenerationKwh: number;
  actualGenerationKwh: number;
  potentialLossKwh: number;
  lossPercent: number;
  possibleCauses: string[];
}

export interface ReportSummary {
  reportType: string;
  title: string;
  period: string;
  generatedAt: string;
  data: unknown;
}

export interface Invoice {
  id: number;
  invoiceNumber: string;
  billingPeriod: string;
  totalMw: number;
  subtotal: number;
  gst: number;
  total: number;
  status: string;
  issueDate: string;
  dueDate: string;
  paidDate?: string;
}

export interface BillingSummary {
  currentPlan: string;
  nextBillingDate: string;
  mwMonitored: number;
  currentInvoiceTotal: number;
  currentInvoiceStatus: string;
  invoices: Invoice[];
}
