namespace SolarShield.Core.DTOs;

public record LoginRequest(string Email, string Password);

public record LoginResponse(
    string Token,
    int UserId,
    string FullName,
    string Email,
    string Role,
    string PreferredLanguage,
    int? OrganizationId,
    string? OrganizationName,
    List<SiteDto> AccessibleSites
);

public record OrganizationDto(
    int Id,
    string Name,
    string Code,
    string? ContactEmail,
    string SubscriptionPlan,
    int MaxPlants,
    int PlantCount,
    int UserCount,
    double TotalCapacityMw,
    bool IsActive,
    DateTime CreatedAt
);

public record CreateOrganizationRequest(
    string Name,
    string Code,
    string? ContactEmail,
    string SubscriptionPlan,
    int MaxPlants
);

public record UpdateOrganizationRequest(
    string? Name,
    string? ContactEmail,
    string? SubscriptionPlan,
    int? MaxPlants,
    bool? IsActive
);

public record CreatePlantRequest(
    int OrganizationId,
    string Name,
    string PlantCode,
    string Location,
    double CapacityMw,
    double Latitude,
    double Longitude,
    double TargetPr
);

public record AdminUserDto(
    int Id,
    string FullName,
    string Email,
    string Phone,
    string Role,
    int? OrganizationId,
    string? OrganizationName,
    bool IsActive,
    List<SiteDto> AssignedSites,
    DateTime CreatedAt
);

public record CreateUserRequest(
    string FullName,
    string Email,
    string Phone,
    string Password,
    string Role,
    int? OrganizationId,
    List<int> SiteIds
);

public record UpdateUserRequest(
    string? FullName,
    string? Phone,
    string? Role,
    bool? IsActive,
    List<int>? SiteIds
);

public record PlatformStatsDto(
    int TotalOrganizations,
    int ActiveOrganizations,
    int TotalPlants,
    double TotalCapacityMw,
    int TotalUsers,
    int OpenFaults,
    int PendingTasks,
    int CriticalAlerts = 0,
    int ActiveSubscriptions = 0,
    int ExpiringSoon = 0,
    decimal MonthlyRevenue = 0
);

public record DashboardSummaryDto(
    int FaultsToday,
    int CriticalFaults,
    int PendingTasks,
    double CurrentPr,
    double SoilingIndex,
    double TodayGenerationKwh,
    double TargetGenerationKwh,
    string SiteName,
    int SiteId,
    double EnergyLossKwh = 0,
    double EnergyLossPercent = 0,
    int OnlineAssets = 0,
    int TotalAssets = 0,
    double EquipmentHealthAvg = 0
);

public record FaultDto(
    int Id,
    int SiteId,
    string SiteName,
    int? ZoneId,
    string? ZoneName,
    string Type,
    string Severity,
    string Status,
    string Title,
    string Description,
    bool IsPredicted,
    double? ConfidenceScore,
    string? AssignedToName,
    int? AssignedToUserId,
    string? FixNotes,
    string? PhotoUrl,
    DateTime DetectedAt,
    DateTime? ResolvedAt
);

public record CreateFaultRequest(
    int SiteId,
    int? ZoneId,
    string Type,
    string Severity,
    string Title,
    string Description,
    bool IsPredicted = false,
    double? ConfidenceScore = null
);

public record UpdateFaultRequest(
    string? Status,
    int? AssignedToUserId,
    string? FixNotes,
    string? PhotoUrl
);

public record AddCommentRequest(string Comment);

public record TaskDto(
    int Id,
    int SiteId,
    string SiteName,
    int? ZoneId,
    string? ZoneName,
    string Title,
    string Description,
    string Status,
    string? AssignedToName,
    int? AssignedToUserId,
    bool IsAutoGenerated,
    DateTime? ScheduledAt,
    DateTime? StartedAt,
    DateTime? CompletedAt,
    string? PhotoUrl,
    string? LocationLabel
);

public record CreateTaskRequest(
    int SiteId,
    int? ZoneId,
    string Title,
    string Description,
    int? AssignedToUserId,
    DateTime? ScheduledAt,
    string? LocationLabel
);

public record UpdateTaskRequest(
    string? Status,
    string? PhotoUrl,
    string? Description
);

public record CleaningScheduleDto(
    int Id,
    int SiteId,
    int ZoneId,
    string ZoneName,
    DateTime ScheduledDate,
    DateTime? CompletedDate,
    double SoilingIndex,
    int Priority,
    bool IsCompleted,
    string? PhotoProofUrl
);

public record ZoneSoilingDto(
    int ZoneId,
    string ZoneName,
    string StringId,
    double SoilingIndex,
    double EstimatedLossPercent,
    DateTime LastUpdated,
    string PriorityLevel
);

public record GenerationAnalyticsDto(
    DateTime Date,
    double ActualKwh,
    double TheoreticalKwh,
    double PerformanceRatio,
    double Irradiance,
    double Temperature
);

public record FaultSummaryDto(
    int Id,
    string Title,
    string Severity,
    string Status,
    string? ZoneName,
    DateTime DetectedAt
);

public record AnalyticsSummaryDto(
    List<GenerationAnalyticsDto> DailyGeneration,
    List<ZoneSoilingDto> ZoneSoiling,
    int TotalFaultsOpen,
    int TasksCompletedThisWeek,
    int TasksPending,
    double AvgPr7Days,
    double TotalActualKwh,
    double TotalTheoreticalKwh,
    double AvgSoilingIndex,
    List<FaultSummaryDto> OpenFaults
);

public record SiteDto(
    int Id,
    string Name,
    string Location,
    double CapacityMw,
    double Latitude,
    double Longitude,
    double TargetPr,
    int OrganizationId = 0,
    string PlantCode = "",
    string? OrganizationName = null
);

public record UserProfileDto(
    int Id,
    string FullName,
    string Email,
    string Phone,
    string Role,
    string PreferredLanguage,
    int? OrganizationId,
    string? OrganizationName,
    List<SiteDto> AssignedSites,
    List<string> Permissions
);

public record NotificationDto(
    int Id,
    string Title,
    string Message,
    bool IsRead,
    DateTime CreatedAt,
    string? LinkType,
    int? LinkId
);

public record AssetDto(
    int Id,
    int SiteId,
    string SiteName,
    int? ZoneId,
    string? ZoneName,
    string AssetCode,
    string Type,
    string SerialNumber,
    string Manufacturer,
    string Model,
    DateTime? InstallationDate,
    double CapacityKw,
    string Location,
    string Status,
    double HealthScore,
    DateTime? LastMaintenanceAt
);

public record ScadaSnapshotDto(
    int SiteId,
    string SiteName,
    double Voltage,
    double Current,
    double PowerKw,
    double Temperature,
    double Frequency,
    string InverterStatus,
    string CommunicationStatus,
    double EnergyGenerationKwh,
    DateTime RecordedAt,
    List<AssetScadaDto> Assets
);

public record AssetScadaDto(
    int AssetId,
    string AssetCode,
    string Type,
    double PowerKw,
    double Temperature,
    string Status,
    double HealthScore
);

public record CompanyDashboardDto(
    int TotalPlants,
    double TotalCapacityMw,
    int OnlineAssets,
    int TotalAssets,
    int CriticalAlerts,
    int OpenMaintenance,
    double TodayGenerationKwh,
    double TargetGenerationKwh,
    double EnergyLossKwh,
    double PlantEfficiency,
    double EquipmentHealth,
    int AiDetectedIssues,
    int ActiveIssues
);

public record OperationsEfficiencyDto(
    int Plants,
    double MwMonitored,
    int Assets,
    int ActiveIssues,
    int AiDetectedIssues,
    int MaintenanceTasks,
    int CriticalTasks,
    int NormalTasks,
    double RemoteMonitoringCoverage
);

public record EnergyLossDto(
    double ExpectedGenerationKwh,
    double ActualGenerationKwh,
    double PotentialLossKwh,
    double LossPercent,
    List<string> PossibleCauses
);

public record ReportSummaryDto(
    string ReportType,
    string Title,
    string Period,
    DateTime GeneratedAt,
    object Data
);

public record BillingSummaryDto(
    string CurrentPlan,
    DateTime NextBillingDate,
    double MwMonitored,
    decimal CurrentInvoiceTotal,
    string CurrentInvoiceStatus,
    List<InvoiceDto> Invoices
);

public record InvoiceDto(
    int Id,
    string InvoiceNumber,
    string BillingPeriod,
    double TotalMw,
    decimal Subtotal,
    decimal Gst,
    decimal Total,
    string Status,
    DateTime IssueDate,
    DateTime DueDate,
    DateTime? PaidDate
);

public record CreateTaskFromFaultRequest(int FaultId, int? AssignedToUserId);
